name: schooll
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <4.0.0"

dependencies:
  anim_search_bar: ^2.0.3
  cached_network_image:
  cloud_firestore: ^0.14.4
  connectivity_plus: ^0.8.1
  cupertino_icons: ^1.0.0
  date_time_picker: ^1.1.0
  dropdown_search: ^0.4.8
  firebase_auth: ^0.18.3+1
  firebase_core: null
  flare_flutter: ^2.0.6
  flrx_validator: ^0.4.0+2
  flutter:
    sdk: flutter
  flutter_svg: null
  fzregex: ^1.0.3
  get: ^4.6.5
  get_storage: ^2.1.1
  google_sign_in: ^4.5.6
  http: ^0.12.2
  iconsax: ^0.0.8
  randomizer: ^0.0.2
  shimmer: ^3.0.0
  url_launcher: ^6.0.5

dev_dependencies:
  flutter_lints: null
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/notification.png
    - assets/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
